[build]
  publish = "public/"
  command = "npm run pre -- $HEAD && npm run build"

[[plugins]]
  # Installs the Lighthouse Build Plugin for all deploy contexts
  package = "@netlify/plugin-lighthouse"

[context.production]
  environment = { NODE_VERSION = "14.15.3", GATSBY_API = 'GATSBY_API_ENDPOINT' }

# Branch Deploy context: all deploys that are not from
# a pull/merge request or from the Production branch 
# will inherit these settings.
[context.branch-deploy.environment]
  NODE_ENV = "development"
  GATSBY_API = 'GATSBY_API_ENDPOINT'